### ISSUE TITLE
google code repo no longer available

### ISSUE THREAD

**Issue by RPCMoritz** [hickinbottoms/gentoo-squeezebox-overlay#5]
- ERROR: media-sound/squeezelite-1.2::squeezebox failed (unpack phase):
-   git-2_update_repo: can't update from https://code.google.com/p/squeezelite

I assume this is because google code is being switched off.

**Comment by RPCMoritz** [comment]
https://github.com/ralph-irving/squeezelite <-- I was able to check out head from that repo.
Sadly there are no version tags or branches yet, so I wasn't able to select a specific revision, but it does look like a good starting point.

**Comment by lmiphay** [comment]
Triode (the author) hasn't been on the forums for quite a while:
http://forums.slimdevices.com/showthread.php?97046-Announce-Squeezelite-a-small-headless-squeezeplay-emulator-for-linux-(alsa-only)&highlight=squeezelite
http://forums.slimdevices.com/search.php?searchid=2333238&pp=
http://forums.slimdevices.com/showthread.php?105599-Triode-s-plugins

ralphy seems to be running the active repo alright:
http://forums.slimdevices.com/showthread.php?105349-Official-Squeezelite-website&p=848737&viewfull=1#post848737

I'll take a look at ralphy's repo for an updated ebuild.

**Comment by lmiphay** [comment]
I have a simple update working (very minimal testing so far) - if it still looks good after the weekend, then I will create a pull request for Stuart.

New version scheme is taken from here: https://github.com/ralph-irving/squeezelite/blob/master/squeezelite.h#L27

The changes in case anyone is interested: https://github.com/lmiphay/gentoo.overlay/commit/e8f90b9dfd989023bfd5e8a47aae5e9ea8bbd514

**Comment by lmiphay** [comment]
Pull request: https://github.com/hickinbottoms/gentoo-squeezebox-overlay/pull/7
